services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    entrypoint: python3 /app/main.py
    volumes:
      - ./config/client.ini:/app/config.ini
      - ./lib:/app/lib
      - ./data:/app/data
    networks: 
      - default
  
networks:
    default:
      external: true
      name: tp1-distribuidos_default
