version: '3'
networks:
  default:
    name: tp1-distribuidos_default
    external: true

services:

  client1:
    image: client:latest
    entrypoint: python3 /app/main.py
    volumes:
      - ./config/client.ini:/app/config.ini
      - ./lib:/app/lib
      - ./data/b68763cb-a531-4f01-b7e8-ed8d571a24e3:/app/data
    environment:
      - CLIENT_ID=b68763cb-a531-4f01-b7e8-ed8d571a24e3
      - OUTPUT_DIR=/app/data/results
    networks:
      - default
