version: '3.12'
services:
  client:
    image: client:latest
    entrypoint: python3 /main.py
    volumes:
      - ./config/client.ini:/config.ini
      - ./data:/data
    networks: 
      - default
  
networks:
    default:
      external: true
      name: tp1-distribuidos_default
