
services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 15672:15672
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 10s

  gateway:
    image: gateway:latest
    entrypoint: python3 /app/main.py
    environment:
      RECORDS_PATH: "/app/backup/records.json"
      RESULTS_PATH: "/app/backup/results.json"
    volumes:
      - ./gateway/backup:/app/backup
    links:
      - rabbitmq
    networks:
      - gateway
      - default

  healthcheck1:
    image: healthcheck:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      ID: "1"
      HOSTNAME: "rabbitmq"

  healthcheck2:
    image: healthcheck:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      ID: "2"
      HOSTNAME: "rabbitmq"

  count_90s_revs_by_title-1:
    container_name: count_90s_revs_by_title-1
    image: count_90s_revs_by_title:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  fiction_category_filter-1:
    container_name: fiction_category_filter-1
    image: fiction_category_filter:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  fiction_avg_nlp_by_title-1:
    container_name: fiction_avg_nlp_by_title-1
    image: fiction_avg_nlp_by_title:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  fiction_title_barrier-1:
    container_name: fiction_title_barrier-1
    image: fiction_title_barrier:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      SHARD_ID: "1"
      DST_ROUTING_KEY: "fiction_titles_shard1"


  90s_top10_filter-1:
    container_name: 90s_top10_filter-1
    image: 90s_top10_filter:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  fiction_reviews_filter-1:
    container_name: fiction_reviews_filter-1
    image: fiction_reviews_filter:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    environment:
      SHARD_ID: "1"
      RABBIT_HOSTNAME: "rabbitmq"
      SRC_QUEUE: "fiction_titles_shard1_queue"
      SRC_EXCHANGE: "fiction_titles_barrier_exchange"
      SRC_ROUTING_KEY: "fiction_titles_shard1"
      DST_EXCHANGE: "fiction_rev_exchange"
      TMP_QUEUES_PREFIX: "reviews_shard1"


  90s_title_barrier-1:
    container_name: 90s_title_barrier-1
    image: 90s_title_barrier:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  computer_books_filter-1:
    container_name: computer_books_filter-1
    image: computer_books_filter:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  author_decades_filter-1:
    container_name: author_decades_filter-1
    image: author_decades_filter:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  fiction_percentile_calculator-1:
    container_name: fiction_percentile_calculator-1
    image: fiction_percentile_calculator:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  title_sharder-1:
    container_name: title_sharder-1
    image: title_sharder:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  title_sharder-2:
    container_name: title_sharder-2
    image: title_sharder:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  title_sharder-3:
    container_name: title_sharder-3
    image: title_sharder:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  90s_title_sharder-1:
    container_name: 90s_title_sharder-1
    image: 90s_title_sharder:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  author_sharder-1:
    container_name: author_sharder-1
    image: author_sharder:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  fiction_review_nlp-1:
    container_name: fiction_review_nlp-1
    image: fiction_review_nlp:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  fiction_title_sharder-1:
    container_name: fiction_title_sharder-1
    image: fiction_title_sharder:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  90s_reviews_filter-1:
    container_name: 90s_reviews_filter-1
    image: 90s_reviews_filter:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

  fiction_percentile_filter-1:
    container_name: fiction_percentile_filter-1
    image: fiction_percentile_filter:latest
    entrypoint: python3 /app/main.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

networks:
  gateway:
    driver: bridge
