services:
  client:
    image: client:latest
    entrypoint: python3 /app/main.py
    volumes:
      - ./config/client.ini:/app/config.ini
      - ./lib:/app/lib
      - ./data:/app/data
    environment:
      - CLIENT_ID=f412e42c-8f80-4d1c-882f-fac6a88d8465
    networks:
      - default 

networks:
  default:
    name: tp1-distribuidos_default
    external: true
