services:
  client:
    image: client:latest
    entrypoint: python3 /app/main.py
    volumes:
      - ./config/client.ini:/app/config.ini
      - ./lib:/app/lib
      - ./data:/app/data
    networks:
      - default

networks:
  default:
    name: tp1-distribuidos_default
    external: true
