services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 15672:15672

  gateway:
    image: gateway:latest
    entrypoint: python3 /app/main.py
    depends_on:
      - rabbitmq
    links:
      - rabbitmq


  client:
    image: client:latest
    entrypoint: python3 /app/main.py
    volumes:
      - ./config/client.ini:/app/config.ini
      - ./lib:/app/lib
      - ./data:/app/data
    depends_on:
      - rabbitmq
    links:
      - rabbitmq