services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 15672:15672
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 10s  

  gateway:
    image: gateway:latest
    entrypoint: python3 /app/main.py
    links:
      - rabbitmq

